### ISSUE TITLE
Feature Request: Improve plugin behavior when Umami backend is temporarily unavailable during startup

### ISSUE THREAD

**Issue by 4ndreasH** [astappiev/traefik-umami-feeder#5]
Hi,

First of all, thanks for this great plugin!

I’m using `traefik-umami-feeder` on a VPS that runs Traefik, while the actual Umami instance is hosted on a separate home server. The connection between the two is established via a tunnel (using [Pangolin](https://github.com/fosrl)), and once both systems are up, everything works perfectly: the plugin can communicate with the Umami API, websites are tracked, etc.

### Problem

The issue arises during **system startup**:

- Traefik starts and loads the plugin immediately.
- At that moment, the Umami backend (on the home server) is not reachable yet because the tunnel isn't fully established.
- The plugin tries to connect and fails.
- As a result, no analytics are collected until I intervene.

### Current workaround

I currently:

- Load the plugin with `disabled: true` in a dynamic config file.
- Wait ~10 seconds until the Umami backend becomes reachable.
- Overwrite the config with `disabled: false`.

This works, but it's fragile and not ideal for automated or production setups.

### Request

It would be helpful if the plugin handled this startup timing issue more robustly.  
For example, by:
- Retrying failed connection attempts during startup
- Delaying initialization
- Or any other approach that avoids complete failure on first contact

I'm not a developer, so I leave the implementation details entirely to you — just hoping to improve resilience in this kind of setup.

Thanks again for your great work!

Best regards,  
**4ndreasH**

**Comment by astappiev** [comment]
Hi @4ndreasH,

I have attempted to solve the issue. Please try the latest version from the main branch and give me some feedback.

To do so (assuming using Docker):
1. Clone the repository to the folder of `docker-compose.yml`
2. Add new volume
```yml
volumes:
      - ./traefik-umami-feeder:/plugins-local/src/github.com/astappiev/traefik-umami-feeder
```
3. Change Traefik plugins loading
```yml
experimental:
  localPlugins:
    umami-feeder:
      moduleName: "github.com/astappiev/traefik-umami-feeder"
```
4. Restart the container
5. You might want to set `debug: true` to see more logs
```yml
http:
  middlewares:
    umami:
      plugin:
        umami-feeder:
          debug: true
          ... other lines ...
```
